# Generated by Django 5.2.7 on 2026-06-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="directmessage",
            new_name="messaging_d_recipie_6af781_idx",
            old_name="messaging_d_recipie_dce174_idx",
        ),
        migrations.RenameIndex(
            model_name="directmessage",
            new_name="messaging_d_sender__75ff09_idx",
            old_name="messaging_d_sender__87244e_idx",
        ),
    ]
