# Generated by Django 5.2.7 on 2026-06-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0006_remove_section_mentor_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="academiccalendar",
            name="resource_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="resource_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="resource_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="registration_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
