# Generated by Django 5.2.7 on 2026-06-19 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_section"),
        ("faculty", "0007_academiccalendar_resource_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academiccalendar",
            name="target_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.section",
            ),
        ),
        migrations.AddField(
            model_name="academiccalendar",
            name="target_year",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "I Year"),
                    (2, "II Year"),
                    (3, "III Year"),
                    (4, "IV Year"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="target_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.section",
            ),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="target_year",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "I Year"),
                    (2, "II Year"),
                    (3, "III Year"),
                    (4, "IV Year"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="target_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.section",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="target_year",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "I Year"),
                    (2, "II Year"),
                    (3, "III Year"),
                    (4, "IV Year"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="academiccalendar",
            name="semester",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="semester",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
