# Generated by Django 5.2.7 on 2026-06-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_target_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="resource_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
